### ISSUE TITLE
Add Spoken Language: French

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher#21]
Do you speak French? Or do you want to learn French (and coding) at the same time? Let's make that possible, but we need your help. If you know of a specific community it would serve to inform our efforts in reaching them, please add to this thread. 

This will allow developers to code in the language of their choice. For instance:
``` python
def add(a,b):
  return a + b
```
could be translated today to:
``` python
def ajouter(a,b):
  return a + b
```
but will be translated to (with your help):
```
définition ajouter(a,b):
  revenir a + b
```

### Instructions

1. Go to the `languages` project folder to find the `start.txt` file
1. Make a duplicate of the `start.txt` file and save it as `LANGUAGE-DIALECT.txt`
- For example, if its French from Canada the file would be `french-canada.txt`
1. Following the format in the file, translate the words in the `start.txt` file to your language.

**When submitting the pull request**:
- The translated file will need to be reviewed by at least 2 different community members to make sure it is appropriate and the best translation that will allow the developer to best understand the foundation of programming. 
- After 2 approved reviews, all 3 contributors will be given credit for the addition of the language when it is merged with the project.

Thank you for making this project reach the community it is meant to empower. We wouldn't be here if it weren't for you, sharing your gifts. Thank you.

**Comment by charberg** [comment]
Hey @madiedgar I could take this one.  Is the mentioned structure in the original comment still accurate? I can't find any references to a start.txt, I assume it's the template file now? I'll go off of @zoomstereo 's PR as an example to start from.

**Comment by madiedgar** [comment]
You're amazing @charberg, finding all my outdated issues. I created this here before we even had the `legesher-translations` repository. Check out this [issue for French translation](https://github.com/legesher/legesher-translations/issues/42)!
