### ISSUE TITLE
Create Tutorial: How to use Github

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher#37]
Need a comprehensive tutorial on how to use Github

**Comment by Kaitou786** [comment]
@madiedgar do we need to make the tutorial of using GitHub from GUI or from CLI?

**Comment by madiedgar** [comment]
Hey @Kaitou786, I made this issue before I publicized the documentation repository. I recreated the issue in the `legesher-docs` repository [here](https://github.com/legesher/legesher-docs/issues/35) and [here](https://github.com/legesher/legesher-docs/issues/36).
