### ISSUE TITLE
marketing: add project to up-for-grabs

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher#53]
## Up-For-Grabs

In order to add Legesher to the project list, we'll have to create a pull request for the repository. This would be a great opportunity for someone who is new to programming and/or github. 

Instructions on what should be included in the pull request can be found in their repo: https://github.com/up-for-grabs/up-for-grabs.net

**Comment by madiedgar** [comment]
Hey @arian81 👋, let's walk through this! Have you made a pull request before or forked a repository? (it's totally okay if you haven't done either!)

**Comment by arian81** [comment]
no I'm totally new to this so neither

**Comment by madiedgar** [comment]
No worries @arian81, We got you! 🎉 

Another question - Do you have [GitHub Desktop](https://desktop.github.com/) or a [text editor](https://atom.io) downloaded?

Step 1️⃣ would be to head over to the https://github.com/up-for-grabs/up-for-grabs.net repository to fork your own copy. 

This is a _very_ [in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) but this might help! They add a lot of context of why you do certain things, which is great, but don't get stuck on any of the terms or methodology. They start going into how you can create a new branch & make changes using `git`. I can walk you through it using GitHub Desktop - which is much easier 👍

**Comment by arian81** [comment]
Yeah I have atom installed but I don't have GitHub desktop I just had git
and by the way I use Ubuntu Linux and a little bit knowledge of python

**Comment by madiedgar** [comment]
GitHub Desktop is a GUI for git - it just makes git look pretty and the functionality of it simple with buttons and pictures instead of typing commands on the terminal. 

### Step 2️⃣: Add the forked repository to your local computer
You will do this by cloning the forked repository to your local computer. This can be done by the command line or through Github Desktop. Just a reminder this will be the `up-for-grabs` repository, not this one. 👍 

### Step 3️⃣: Create a branch to add your changes
This is where the in-depth tutorial goes in pretty deep, and gets kinda confusing. You can actually create a branch within the repository itself or within Github Desktop to make it a simpler task. 
![Screen Shot 2019-10-04 at 3 18 51 PM](https://user-images.githubusercontent.com/7844510/66233867-4bb57700-e6ba-11e9-961e-ced1d76979cb.png)

**Comment by arian81** [comment]
so i made a branch called legesher on the fork i cloned to my system. now what should i do?

**Comment by madiedgar** [comment]
Awesome @arian81! You'll want to `publish branch`. Then when you make edits on your text editor, be sure to check they are made on your new `legesher` branch (mine says `master`). 
![Screen Shot 2019-10-05 at 5 25 49 PM](https://user-images.githubusercontent.com/7844510/66261076-3cefc280-e795-11e9-957a-d04337802a84.png)

Now, you'll want to see what the `up-for-grabs` repo is looking for their pull request. When you feel confident about your changes, commit them. Then we'll start the pull request 👍

**Comment by Lawrence4code** [comment]
Hi, I'd like to work on this, please.

**Comment by charberg** [comment]
Hey @madiedgar, I can get this one done if you'd like. I've joined the Discord as well, if you want me to run the PR by you first, and/or I could just add you as a reviewer to the PR.

**Comment by charberg** [comment]
@madiedgar Looks like this one is already done, see PR https://github.com/up-for-grabs/up-for-grabs.net/pull/1558 by @Beomus

**Comment by madiedgar** [comment]
Oh awesome!! Thank you for looking into this!! Thanks @beomus for your contribution! @Lawrence4code and @arian81, I'll add some additional issues you can start on 😄
