### ISSUE TITLE
marketing: add repository to "awesome-for-non-programmers"

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher#54]
## Awesome-For-Non-Programmers

Would love to add this repository to the [`awesome-for-non-programmers`](https://github.com/szabgab/awesome-for-non-programmers) repository for non programmers to learn about open source opportunities that don't require a technical background. 

With the Legesher project, there are a lot of opportunities for people of all backgrounds to contribute the skills they either want to grow in or give back. With a strong emphasis on written language translation, individuals who are bilingual have a great space to contribute. Individuals who want to grow in community development, marketing, writing impactful pieces of insight, or just want to learn more about the tech world have ample amounts of opportunities here as well! 

More details can be found in their pull request template.

**Comment by AlexandruBuhai** [comment]
Submitted a PR here https://github.com/szabgab/awesome-for-non-programmers/pull/28.

**Comment by szabgab** [comment]
I don't see why this project should be listed in the awesome-for-non-programmers.

**Comment by madiedgar** [comment]
Hey @szabgab 👋! I definitely see where you're coming from, having so many pull requests. I apologize for the spam-like activity, for that was not our intention.

One of our intentions this hacktoberfest is to introduce new programmers & non-programmers into the open source community. We created simple issues in each of our repositories that non-programmers could take on with the support from other people in the community and from seeing previous examples (I remember making my first pull request was really nerve wracking!). 

Each of our repositories recognize [all contributors](https://allcontributors.org)- even those who don't push code. 😄 From my understanding, this why your repository `awesome-for-non-programmers` would be applicable for each of our repositories. Hope this helps!

**Comment by szabgab** [comment]
Well, yes I saw your intentation and it is admirable :clap: but  I also looked at the web site and it confused me. The site only seems to indicated e-mail collection.

So it is unclear to me what does your project do?

The only thing I really noticed (which pained me) is that it is called legesher instead of legasher as the IPA spelling and the pronunciation of the hebrew word would suggest

**Comment by madiedgar** [comment]
We're still working on our beta version and wanted to welcome contributions from individuals from all backgrounds.

Sorry for the inconvenience, I closed all our issues referencing your repo. All the best!

**Comment by Navneet78** [comment]
sorry @madiedgar and @szabgab it was my bad for spelling also I was learning to create pull request at that time. Now I am familiar with opensource thanks @madiedgar
