### ISSUE TITLE
Add an Issue Template

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher#6]
It's not the easiest thing to get involved in a new open source project, especially when you're not familiar to the platform or open source in general. There are different ways people can get involved:

1. Reporting a bug  
1. Suggesting a new feature  
1. Creating a pull request

More seasoned open source contributors might go straight to creating their first pull request, so adding helpful templates to a repository that makes it easier for everyone to get involved, regardless of their previous experience.

Let's create issue templates for the list above: 

- [x] Reporting a bug  
- [x] Suggesting a new feature  
- [x] Creating a pull request

**Comment by underscoreanuj** [comment]
I would like to work on this.

**Comment by madiedgar** [comment]
That would be awesome @underscoreanuj! I think this repository has issue and pull request templates found in `.github/*` folder, but I think they definitely need to be refined a bit. Once we have those all settled, I'd love to include those on each of the repositories in this organization! 😄

**Comment by madiedgar** [comment]
Closing this as it was resolved by @underscoreanuj in #69
