### ISSUE TITLE
docs: update copy for README

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher#92]
## README Copy Updates

Along with any copy edits you may find, please include the following in your PR:
- [ ] delete the "sponsors | 4" badge
- [ ] update the "sponsor | @withmadico" to be "sponsor | madiedgar" with this link (https://github.com/sponsors/madiedgar)
- [ ] delete the "twitch | watch" badge
- [ ] delete the "read" badge 
- [ ] modify the link to the "mailchimp | subscribe" button to go to (https://mailchi.mp/083d8b2e0e12/legesher-landing-page)

As always, reach out if you have any questions 👍

**Comment by atom19-i** [comment]
@madiedgar i would like to work on this issue. can i ask how can i run the project on vscode? when i typed npm start, it didnt run. 

here's a screenshot of the terminal : 
![image](https://user-images.githubusercontent.com/54570007/139485340-d30684aa-31ee-41a8-8b0a-27a14b120261.png)
