### ISSUE TITLE
Upgrade the Issue Template to use GitHub Issue forms

### ISSUE THREAD

**Issue by Rutam21** [legesher/legesher#94]
## Introduction
GitHub has recently rolled out a public beta for their issue forms feature. This would allow us to create interactive issue templates and validate them.

Legesher currently uses the older issue template format. The task is to create GitHub issue forms for this repository. 

## Tasks summary:
 - [ ] Fork & clone this repository
 - [ ] Prepare bug report issue form in .github/ISSUE_TEMPLATE/bug.yaml
 - [ ] Prepare documentation issue form in .github/ISSUE_TEMPLATE/documentation.yaml
 - [ ] Prepare feature request issue form in .github/ISSUE_TEMPLATE/feature.yaml
 - [ ] Push changes to master and test issue forms on your fork
 - [ ] Submit pull request

**Comment by Rutam21** [comment]
@madiedgar Please have a look at this issue and let me know your thoughts on this. Also, add the appropriate labels for `hacktoberfest`.

**Comment by madiedgar** [comment]
thank you @Rutam21 for opening this issue. I will take a look at your PR. 👍
