### ISSUE TITLE
📚 Documentation: Links for Submitting Issues broken

### ISSUE THREAD

**Issue by shahkv95** [legesher/legesher#99]
### 💭 Description

The links under the Submitting Issues section in the Contributing.md files are broken and throws 404 errors. We need to update them to ensure proper reference to the newcomers. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/legesher/legesher/blob/master/CODE_OF_CONDUCT.md)

**Comment by TomerPacific** [comment]
@madiedgar  - I don't think this issue is still relevant as the links are working. I suggest we can close it.
